apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ubuntu
  namespace: simple-pod-new
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: kamendev/simplev3
        volumeMounts:
        - mountPath: /var/lib
          name: nginx-vol-nginx-0
        - mountPath: /var/www
          name: nginx-vol-nginx-0
        - mountPath: /home/linux
          name: nginx-vol-nginx-0
      volumes:
      - name: nginx-vol-nginx-0
        persistentVolumeClaim:
          claimName: nginx-vol-nginx-0
