apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    component: web
spec:
      containers:
      - name: nginx
        image: kamendev/simplev2
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: nginx-vol-nginx-0
        - mountPath: /var/www
          name: nginx-vol-nginx-0
      volumes:
      - name: nginx-vol-nginx-0
        persistentVolumeClaim:
          claimName: nginx-vol-nginx-0
